version: '3.0'
services:
  web:
    image: nginx
    volumes:
      - "${LOCAL_DIR}:/usr/share/nginx/html"
    ports:
      - "8081:80"
    networks:
      - bianca_pasarea
networks:
  bianca_pasarea:
